version: '3.4'

services:
  project-management-api:
    image: ${DOCKER_REGISTRY-}projectmanagementapi
    build:
      context: .
      dockerfile: project-management-api/Dockerfile
    links:
        - db
    ports:
        - 5000:8080
        - 5001:8081


  db:
    container_name: "db"
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Qwerty123!"
        ACCEPT_EULA: "Y"

  adminer:
        image: adminer
        restart: always
        links:
            - db:db
        ports:
            - 5002:8080